# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_firstname', models.CharField(max_length=50)),
                ('person_lastname', models.CharField(max_length=50)),
                ('person_city', models.CharField(max_length=50)),
                ('person_age', models.IntegerField(default=0)),
            ],
        ),
    ]
