# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_avtar',
            field=models.CharField(default='http://free-profile-pics.com/profile-pictures/01232014/download/albert-einstein-profile-picture-512x512.png', max_length=256),
        ),
    ]
